-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 14:30:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cogip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cogip` DEFAULT CHARACTER SET utf8 ;
USE `cogip` ;

-- -----------------------------------------------------
-- Table `cogip`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cogip`.`societe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`societe` (
  `idSociete` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(90) NOT NULL,
  `pays` VARCHAR(45) NOT NULL,
  `tva` INT ZEROFILL NOT NULL,
  `phone` INT ZEROFILL NOT NULL,
  `type_idType` INT NOT NULL,
  PRIMARY KEY (`idSociete`, `type_idType`),
  CONSTRAINT `fk_societe_type`
    FOREIGN KEY (`type_idType`)
    REFERENCES `cogip`.`type` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_societe_type_idx` ON `cogip`.`societe` (`type_idType` ASC);


-- -----------------------------------------------------
-- Table `cogip`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `firstName` VARCHAR(30) NOT NULL,
  `phone` INT ZEROFILL NULL,
  `email` VARCHAR(100) NULL,
  `societe_idSociete` INT NOT NULL,
  PRIMARY KEY (`idPersonne`, `societe_idSociete`),
  CONSTRAINT `fk_personne_societe1`
    FOREIGN KEY (`societe_idSociete`)
    REFERENCES `cogip`.`societe` (`idSociete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_personne_societe1_idx` ON `cogip`.`personne` (`societe_idSociete` ASC);


-- -----------------------------------------------------
-- Table `cogip`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cogip`.`facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT COMMENT 'Numero de la commande',
  `date` DATE NOT NULL,
  `details` TEXT NULL,
  `societe_idSociete` INT NOT NULL,
  `personne_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idFacture`, `societe_idSociete`, `personne_idPersonne`),
  CONSTRAINT `fk_facture_societe1`
    FOREIGN KEY (`societe_idSociete`)
    REFERENCES `cogip`.`societe` (`idSociete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_personne1`
    FOREIGN KEY (`personne_idPersonne`)
    REFERENCES `cogip`.`personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_facture_societe1_idx` ON `cogip`.`facture` (`societe_idSociete` ASC);

CREATE INDEX `fk_facture_personne1_idx` ON `cogip`.`facture` (`personne_idPersonne` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
